USE `student`;
/* task 5. */;
insert into `passport` values (1, '12345678901234', 3811878, 'МР', 'Московское РОВД г.Минска', (select id_country from country where country.country_name = 'Беларусь'), '2024-07-12', 'мужской', '1994-07-12'),
(2, '34345674501234', 9861878, 'НР', 'РОВД г.Несвижа', (select id_country from country where country.country_name = 'Беларусь'), '2024-06-14', 'мужской', '1998-06-12'), (3, '12555558901234', 5551878, 'МР', 'Московское РОВД г.Минска', (select id_country from country where country.country_name = 'Беларусь'), '2025-05-15', 'женский', '1999-09-19'),
(4, '44345644901234', 4411448, 'МР', 'Московское РОВД г.Минска', (select id_country from country where country.country_name = 'Беларусь'), '2029-07-12', 'мужской', '1999-09-19'), (5, '43215678904321', 3121128, 'СР', 'РОВД г.Слуцка', (select id_country from country where country.country_name = 'Беларусь'), '2025-05-15', 'мужской', '1998-09-12'),
(6, '33345678901333', 3331838, 'МР', 'Московское РОВД г.Минска', (select id_country from country where country.country_name = 'Беларусь'), '2027-05-15', 'женский', '1999-12-11'), (7, '44445678401434', 3111871, 'МР', 'Московское РОВД г.Минска', (select id_country from country where country.country_name = 'Беларусь'), '2021-01-11', 'мужской', '1998-01-11'),
(8, '88345678801238', 3888878, 'МР', 'Московское РОВД г.Минска', (select id_country from country where country.country_name = 'Беларусь'), '2028-08-18', 'мужской', '1998-08-18'), (9, '99945678901999', 3999878, 'МР', 'Московское РОВД г.Минска', (select id_country from country where country.country_name = 'Беларусь'), '2029-07-12', 'мужской', '1999-09-12'),
(10, '12234678900034', 3800878, 'МР', 'Московское РОВД г.Минска', (select id_country from country where country.country_name = 'Беларусь'), '2026-06-22', 'мужской', '1998-05-15');


insert into `adress` values (1, (select id_country from country where country.country_name = 'Беларусь'), (select id_locality from locality where locality.locality_name = 'Минск'), (select id_street from street where street.street_name = 'Слободская'), 3, 2, 1, 220025, 205246, 738121, 'kauud@gmal.com', (select id_district from district where district.district_name = 'Минский'), (select id_area from area where area.area_name = 'Минская'), '1', '1'), 
(2, (select id_country from country where country.country_name = 'Беларусь'), (select id_locality from locality where locality.locality_name = 'Минск'), (select id_street from street where street.street_name = 'Есенина'), 32, 22, 1, 220022, 2052246, 7381221, 'еуекd@gmal.com', (select id_district from district where district.district_name = 'Минский'), (select id_area from area where area.area_name = 'Минская'), '', ''), 
(3, (select id_country from country where country.country_name = 'Беларусь'), (select id_locality from locality where locality.locality_name = 'Брест'), (select id_street from street where street.street_name = 'Слободская'), 35, 6, 2, 220025, 205246, 738121, 'kaкud@gmal.com', (select id_district from district where district.district_name = 'Минский'), (select id_area from area where area.area_name = 'Брестская'), '', ''),
(4, (select id_country from country where country.country_name = 'Беларусь'), (select id_locality from locality where locality.locality_name = 'Минск'), (select id_street from street where street.street_name = 'Якуба Коласа'), 11, 5, 2, 220015, 205246, 738121, 'kккuк@gmal.com', (select id_district from district where district.district_name = 'Минский'), (select id_area from area where area.area_name = 'Минская'), '3', '4'),
(5, (select id_country from country where country.country_name = 'Беларусь'), (select id_locality from locality where locality.locality_name = 'Минск'), (select id_street from street where street.street_name = 'Слободская'), 65, 7, 7, 220035, 205246, 738121, 'ккud@gmal.com', (select id_district from district where district.district_name = 'Минский'), (select id_area from area where area.area_name = 'Минская'), '', ''),
(6, (select id_country from country where country.country_name = 'Беларусь'), (select id_locality from locality where locality.locality_name = 'Лида'), (select id_street from street where street.street_name = 'Победителей'), 53, 2, 4, 220045, 205246, 738121, 'kaууud@gmal.com', (select id_district from district where district.district_name = 'Минский'), (select id_area from area where area.area_name = 'Брестская'), '', ''),
(7, (select id_country from country where country.country_name = 'Беларусь'), (select id_locality from locality where locality.locality_name = 'Минск'), (select id_street from street where street.street_name = 'Слободская'), 24, 6, 5, 220055, 205246, 738121, 'weq@gmal.com', (select id_district from district where district.district_name = 'Минский'), (select id_area from area where area.area_name = 'Минская'), '', ''),
(8, (select id_country from country where country.country_name = 'Беларусь'), (select id_locality from locality where locality.locality_name = 'Минск'), (select id_street from street where street.street_name = 'Есенина'), 65, 9, 5, 220015, 205246, 738121, 'rtr@gmal.com', (select id_district from district where district.district_name = 'Минский'), (select id_area from area where area.area_name = 'Минская'), '', ''),
(9, (select id_country from country where country.country_name = 'Беларусь'), (select id_locality from locality where locality.locality_name = 'Минск'), (select id_street from street where street.street_name = 'Космонавтов'), 23, 34, 3, 220025, 205246, 738121, 'trg@gmal.com', (select id_district from district where district.district_name = 'Минский'), (select id_area from area where area.area_name = 'Минская'), '', ''),
(10, (select id_country from country where country.country_name = 'Беларусь'), (select id_locality from locality where locality.locality_name = 'Минск'), (select id_street from street where street.street_name = 'Слободская'), 87, 87, 2, 220025, 205246, 738121, 'hrhr@gmal.com', (select id_district from district where district.district_name = 'Минский'), (select id_area from area where area.area_name = 'Минская'), '', '');
/*ORDER BY RAND()LIMIT 1*/
insert into `student` values (1, 750012, 3, 'бюджет', 'дневная', '2016-12-11', '2026-12-11', CURRENT_TIMESTAMP, (select id from name1 ORDER BY RAND()LIMIT 1), (select id from name2 ORDER BY RAND()LIMIT 1), (select id from name3 ORDER BY RAND()LIMIT 1), (select id from adress ORDER BY RAND()LIMIT 1), (select id from passport ORDER BY RAND()LIMIT 1), (select id from university ORDER BY RAND()LIMIT 1), (select id from faculty ORDER BY RAND()LIMIT 1), (select id from speciality ORDER BY RAND()LIMIT 1), 13324),
(2, 750012, 3, 'бюджет', 'дневная', '2016-12-11', '2026-12-11', CURRENT_TIMESTAMP, (select id from name1 ORDER BY RAND()LIMIT 1), (select id from name2 ORDER BY RAND()LIMIT 1), (select id from name3 ORDER BY RAND()LIMIT 1), (select id from adress ORDER BY RAND()LIMIT 1), (select id from passport ORDER BY RAND()LIMIT 1), (select id from university ORDER BY RAND()LIMIT 1), (select id from faculty ORDER BY RAND()LIMIT 1), (select id from speciality ORDER BY RAND()LIMIT 1), 13324),
(3, 750432, 2, 'бюджет', 'дневная', '2016-12-11', '2026-12-11', CURRENT_TIMESTAMP, (select id from name1 ORDER BY RAND()LIMIT 1), (select id from name2 ORDER BY RAND()LIMIT 1), (select id from name3 ORDER BY RAND()LIMIT 1), (select id from adress ORDER BY RAND()LIMIT 1), (select id from passport ORDER BY RAND()LIMIT 1), (select id from university ORDER BY RAND()LIMIT 1), (select id from faculty ORDER BY RAND()LIMIT 1), (select id from speciality ORDER BY RAND()LIMIT 1), 13324),
(4, 750342, 1, 'бюджет', 'дневная', '2018-11-11', '2026-12-11', CURRENT_TIMESTAMP, (select id from name1 ORDER BY RAND()LIMIT 1), (select id from name2 ORDER BY RAND()LIMIT 1), (select id from name3 ORDER BY RAND()LIMIT 1), (select id from adress ORDER BY RAND()LIMIT 1), (select id from passport ORDER BY RAND()LIMIT 1), (select id from university ORDER BY RAND()LIMIT 1), (select id from faculty ORDER BY RAND()LIMIT 1), (select id from speciality ORDER BY RAND()LIMIT 1), 42424),
(5, 550341, 4, 'бюджет', 'дневная', '2019-12-11', '2026-12-11', CURRENT_TIMESTAMP, (select id from name1 ORDER BY RAND()LIMIT 1), (select id from name2 ORDER BY RAND()LIMIT 1), (select id from name3 ORDER BY RAND()LIMIT 1), (select id from adress ORDER BY RAND()LIMIT 1), (select id from passport ORDER BY RAND()LIMIT 1), (select id from university ORDER BY RAND()LIMIT 1), (select id from faculty ORDER BY RAND()LIMIT 1), (select id from speciality ORDER BY RAND()LIMIT 1), 1345),
(6, 450011, 2, 'бюджет', 'дневная', '2017-11-11', '2026-12-11', CURRENT_TIMESTAMP, (select id from name1 ORDER BY RAND()LIMIT 1), (select id from name2 ORDER BY RAND()LIMIT 1), (select id from name3 ORDER BY RAND()LIMIT 1), (select id from adress ORDER BY RAND()LIMIT 1), (select id from passport ORDER BY RAND()LIMIT 1), (select id from university ORDER BY RAND()LIMIT 1), (select id from faculty ORDER BY RAND()LIMIT 1), (select id from speciality ORDER BY RAND()LIMIT 1), 1242324),
(7, 650012, 3, 'бюджет', 'дневная', '2019-12-11', '2026-12-11', CURRENT_TIMESTAMP, (select id from name1 ORDER BY RAND()LIMIT 1), (select id from name2 ORDER BY RAND()LIMIT 1), (select id from name3 ORDER BY RAND()LIMIT 1), (select id from adress ORDER BY RAND()LIMIT 1), (select id from passport ORDER BY RAND()LIMIT 1), (select id from university ORDER BY RAND()LIMIT 1), (select id from faculty ORDER BY RAND()LIMIT 1), (select id from speciality ORDER BY RAND()LIMIT 1), 87324),
(8, 670032, 2, 'бюджет', 'дневная', '2019-11-11', '2026-12-11', CURRENT_TIMESTAMP, (select id from name1 ORDER BY RAND()LIMIT 1), (select id from name2 ORDER BY RAND()LIMIT 1), (select id from name3 ORDER BY RAND()LIMIT 1), (select id from adress ORDER BY RAND()LIMIT 1), (select id from passport ORDER BY RAND()LIMIT 1), (select id from university ORDER BY RAND()LIMIT 1), (select id from faculty ORDER BY RAND()LIMIT 1), (select id from speciality ORDER BY RAND()LIMIT 1), 1984),
(9, 785046, 3, 'бюджет', 'дневная', '2018-12-11', '2026-12-11', CURRENT_TIMESTAMP, (select id from name1 ORDER BY RAND()LIMIT 1), (select id from name2 ORDER BY RAND()LIMIT 1), (select id from name3 ORDER BY RAND()LIMIT 1), (select id from adress ORDER BY RAND()LIMIT 1), (select id from passport ORDER BY RAND()LIMIT 1), (select id from university ORDER BY RAND()LIMIT 1), (select id from faculty ORDER BY RAND()LIMIT 1), (select id from speciality ORDER BY RAND()LIMIT 1), 9824),
(10, 778012, 2, 'бюджет', 'дневная', '2017-12-11', '2026-12-11', CURRENT_TIMESTAMP, (select id from name1 ORDER BY RAND()LIMIT 1), (select id from name2 ORDER BY RAND()LIMIT 1), (select id from name3 ORDER BY RAND()LIMIT 1), (select id from adress ORDER BY RAND()LIMIT 1), (select id from passport ORDER BY RAND()LIMIT 1), (select id from university ORDER BY RAND()LIMIT 1), (select id from faculty ORDER BY RAND()LIMIT 1), (select id from speciality ORDER BY RAND()LIMIT 1), 89324);